services:
  model:
    build:
      dockerfile: model.dockerfile
    image: model-img:latest
    container_name: model-sign
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1']
              capabilities: [gpu]
    volumes:
      - /share/sign-ml/bertseq2seq:/home/bertseq2seq